name: projectname
repo: git://github.com/username/projectname.git
deploy_user: deploy
user: projectuser
access_users: [deploy, projectuser, user1, user2, user3]
group: group
theme: themename
domain: domain.com

stage:
  dev:
    ip: 127.0.0.1
    http_port: 8080
    ssh_port: 2222
    user: vagrant
    upload_url_path: 
    upload_path: 
  staging:
    ip: 0.0.0.0
    ssh_port: 0
    user: deploy
    upload_url_path: 
    upload_path: 
  production:
    ip: 0.0.0.0
    ssh_port: 0
    user: deploy
    upload_url_path: 
    upload_path: 
